{% set name = "djangocms-attributes-field" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb56fdd1079ca2b478e38c86291e11095c9cb9215d621626849627eb76e39c95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-cms >=3.7

test:
  imports:
    - djangocms_attributes_field
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-cms/djangocms-attributes-field/
  summary: Adds attributes to Django models.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
