{% set name = "djangocms-attributes-field" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangocms-attributes-field-{{ version }}.tar.gz
  sha256: 70cbcb8e826b5a6bceba348119ddc01fa5910af4cb4002eb9895d311950b0d9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-cms >=3.7

test:
  imports:
    - djangocms_attributes_field
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-cms/djangocms-attributes-field/
  summary: Adds attributes to Django models.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
